### ISSUE TITLE
Ability to use appengine SDK not in mvn

### ISSUE THREAD

**Issue by wmacgyver** [gaelyk/gaelyk#202]
Sometimes I want to use beta build of GAE SDK. or sometimes I want to use SDK that's not yet in mvn. etc. 

So it would be useful sometimes if you can use pre-installed GAE SDK in local file system.

currently this can be work around by first do gradle gaeRun, and then go to WEB-INF/lib and then replace the jars. after that, run the devappserver with src/main/webapps as target

**Comment by codeconsole** [comment]
All you have to do is build then run appcfg.sh
    gradle build
    appcfg.sh build/exploded-app
