### ISSUE TITLE
 appengineRun task hangs

### ISSUE THREAD

**Issue by sh4d0000** [gaelyk/gaelyk#211]
Hello,
I'm not sure if this is an expected behaviour. I've downloaded the template project and when I execute gradlew appengineRun the server starts but the task hangs. I need to create a gradle task that depends on appengineRun but since it hangs the other task never runs 

:appengineRun
Executing [/usr/lib/jvm/java-7-oracle/jre/bin/java, -javaagent:/home/sh4d/.gradle/appengine-sdk/appengine-java-sdk-1.9.4/lib/agent/appengine-agent.jar, -Xbootclasspath/p:/home/sh4d/.gradle/appengine-sdk/appengine-java-sdk-1.9.4/lib/override/appengine-dev-jdk-overrides.jar, -classpath, /home/sh4d/dev/projects/gaelyk/gradle/wrapper/gradle-wrapper.jar:/home/sh4d/.gradle/appengine-sdk/appengine-java-sdk-1.9.4/lib/appengine-tools-api.jar, com.google.appengine.tools.development.DevAppServerMain, --property=kickstart.user.dir=/home/sh4d/dev/projects/gaelyk, --port=8080, --address=localhost, --allow_remote_shutdown, /home/sh4d/dev/projects/gaelyk/build/exploded-app]
********************************************************
There is a new version of the SDK available.
-----------
Latest SDK:
Release: 1.9.7
Timestamp: Wed Jun 04 22:20:17 CEST 2014
API versions: [1.0]

-----------
Your SDK:
Release: 1.9.4
Timestamp: Thu Apr 24 01:55:18 CEST 2014
API versions: [1.0]

-----------
Please visit https://developers.google.com/appengine/downloads for the latest SDK.
********************************************************
Jul 24, 2014 6:41:28 PM com.google.apphosting.utils.config.AppEngineWebXmlReader readAppEngineWebXml
INFO: Successfully processed /home/sh4d/dev/projects/gaelyk/build/exploded-app/WEB-INF/appengine-web.xml
Jul 24, 2014 6:41:28 PM com.google.apphosting.utils.config.AbstractConfigXmlReader readConfigXml
INFO: Successfully processed /home/sh4d/dev/projects/gaelyk/build/exploded-app/WEB-INF/web.xml
Jul 24, 2014 6:41:28 PM com.google.appengine.tools.development.SystemPropertiesManager setSystemProperties
INFO: Overwriting system property key 'java.util.logging.config.file', value '/home/sh4d/.gradle/appengine-sdk/appengine-java-sdk-1.9.4/config/sdk/logging.properties' with value 'WEB-INF/logging.properties' from '/home/sh4d/dev/projects/gaelyk/build/exploded-app/WEB-INF/appengine-web.xml'
Jul 24, 2014 6:41:28 PM com.google.appengine.tools.development.SystemPropertiesManager setSystemProperties
INFO: Overwriting system property key 'file.encoding', value 'UTF-8' with value 'UTF-8' from '/home/sh4d/dev/projects/gaelyk/build/exploded-app/WEB-INF/appengine-web.xml'
Jul 24, 2014 6:41:28 PM com.google.apphosting.utils.jetty.JettyLogger info
INFO: Logging to JettyLogger(null) via com.google.apphosting.utils.jetty.JettyLogger
Jul 24, 2014 6:41:28 PM com.google.apphosting.utils.jetty.JettyLogger info
INFO: jetty-6.1.x
Jul 24, 2014 6:41:33 PM com.google.appengine.tools.development.ApiProxyLocalImpl log
INFO: javax.servlet.ServletContext log: Groovy servlet initialized on groovy.util.GroovyScriptEngine@505d3af5.
Jul 24, 2014 6:41:33 PM com.google.appengine.tools.development.ApiProxyLocalImpl log
INFO: javax.servlet.ServletContext log: TemplateServlet: Servlet groovyx.gaelyk.GaelykTemplateServlet initialized on class groovy.text.SimpleTemplateEngine
Jul 24, 2014 6:41:33 PM com.google.apphosting.utils.jetty.JettyLogger info
INFO: Started SelectChannelConnector@localhost:8080
Jul 24, 2014 6:41:33 PM com.google.appengine.tools.development.AbstractModule startup
INFO: Module instance default is running at http://localhost:8080/
Jul 24, 2014 6:41:33 PM com.google.appengine.tools.development.AbstractModule startup
INFO: The admin console is running at http://localhost:8080/_ah/admin
Jul 24, 2014 6:41:33 PM com.google.appengine.tools.development.DevAppServerImpl doStart
INFO: Dev App Server is now running
> Building 90% > :appengineRun

**Comment by codeconsole** [comment]
did you get this working?  I haven't had an issues running my projects
