### ISSUE TITLE
Example on how to use backend service or background threading

### ISSUE THREAD

**Issue by paradoxalan** [gaelyk/gaelyk#224]
Hello

I need to do backgorund async processing with thread spawn by request.
When I try to use gae ThreadManager it throws an Exception: This is only available on backend instances, something like that.
I'm having a hard time through gae docs for Java on how to use backend.
Can someone with experinece on this guide me to the right path on achieving this task
Either config properly backend or another method of background thread.
Thanks

**Comment by musketyr** [comment]
There has been lot of changes in backends (which are considered deprecated at the moment) but I believe you need to declare instance type as B<something> 

https://cloud.google.com/appengine/docs/standard/
