### ISSUE TITLE
Application deployment failed. Message: Deployments using appcfg are no longer supported. See https://cloud.google.com/appengine/docs/deprecations

### ISSUE THREAD

**Issue by paradoxalan** [gaelyk/gaelyk#235]
Getting the message in the title when trying to update my app.
Google says i have to use the SDK Cloud now.
I'm following the steps in the docs of Google to install the SDK Cloud, which will get the supported tools by Oct/2020 to interact with App Engine.
But i have no ideia what to change in Gaelyk and gradle configs. to correctly update the app now.
Did someone when through this, can help me with that.
Thanks guys.

**Comment by paradoxalan** [comment]
As i'm searching for solution, as i can see i just have to change a bit the build.gradle file.
With instructions from this link https://cloud.google.com/appengine/docs/standard/java/using-gradle?hl=pt-br, it shows me the modifications:
new dependency within buildscript:
classpath 'com.google.cloud.tools:appengine-gradle-plugin:2.2.0'

new plugin apply:
apply plugin: 'com.google.cloud.tools.appengine' // gradle tasks

new block within appengine
deploy {
      version = '21'
      project = "rastreio-174117"
  }

But i'm getting conflict of gradle tasks with same name already defined, as i can see the new plugin apply must define the tasks, but already defined by another apply command (gaelyk maybe).

How can i proceed here now?
Thanks

**Comment by musketyr** [comment]
I believe this has been discussed here - https://groups.google.com/g/gaelyk/c/7hdvZCi3RBE

**Comment by paradoxalan** [comment]
Well ok i'll take a look in there.
Thanks for reply.

**Comment by paradoxalan** [comment]
I was able to get it working following that google group discussion.
Thanks musketyr.

**Comment by musketyr** [comment]
Sure thing!
